# The input directory, relative to this file's path.
dir = "./"
# The output directory, relative to the input directory.
output_dir = "output/"
# Glob patterns for files in the input directory that should be ignored.
exclude = []
# Glob patterns for template files.
templates = ["templates/**/*.xml"]
# Glob patterns for snipppet files.
snippets = ["snippets/**/*.xml"]
# Glob patterns for dataset files.
datasets = ["data/*.xml"]
# Glob patterns for data row files.
datarows = ["data/*/**/*.xml"]
# Glob patterns for page files.
pages = ["**/*.xml"]
# Glob patterns for static assets files.
assets = ["assets/**/*"]
